"""empty message

Revision ID: 401afc4c7a93
Revises: 701b53f146cd
Create Date: 2016-05-25 00:15:57.403020

"""

# revision identifiers, used by Alembic.
revision = '401afc4c7a93'
down_revision = '701b53f146cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'social_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'social_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###
